"""empty message

Revision ID: c250d73cc544
Revises: 
Create Date: 2023-05-03 22:45:11.207237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c250d73cc544'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_cards')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_cards',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('card_name', sa.TEXT(), nullable=True),
    sa.Column('card_number', sa.INTEGER(), nullable=True),
    sa.Column('exp_date', sa.TEXT(), nullable=True),
    sa.Column('cvc', sa.INTEGER(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
